// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class EnvironmentsTransport: EnvironmentsStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://composer.googleapis.com",
      )
    }

    public func createEnvironment(
      request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/environments"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.environment {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.Environment.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listEnvironments(
      request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/environments"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func updateEnvironment(
      request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.environment {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteEnvironment(
      request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func executeAirflowCommand(
      request: ExecuteAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):executeAirflowCommand"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func stopAirflowCommand(
      request: StopAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):stopAirflowCommand"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func pollAirflowCommand(
      request: PollAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):pollAirflowCommand"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/workloads"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func checkUpgrade(
      request: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):checkUpgrade"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createUserWorkloadsSecret(
      request: CreateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/userWorkloadsSecrets"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.userWorkloadsSecret {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getUserWorkloadsSecret(
      request: GetUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listUserWorkloadsSecrets(
      request: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/userWorkloadsSecrets"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func updateUserWorkloadsSecret(
      request: UpdateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.userWorkloadsSecret.map({ $0.name }),
          !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.user_workloads_secret.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PUT)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.userWorkloadsSecret {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func deleteUserWorkloadsSecret(
      request: DeleteUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createUserWorkloadsConfigMap(
      request: CreateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/userWorkloadsConfigMaps"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.userWorkloadsConfigMap {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getUserWorkloadsConfigMap(
      request: GetUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listUserWorkloadsConfigMaps(
      request: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/userWorkloadsConfigMaps"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func updateUserWorkloadsConfigMap(
      request: UpdateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.userWorkloadsConfigMap.map({ $0.name }),
          !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.user_workloads_config_map.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PUT)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.userWorkloadsConfigMap {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func deleteUserWorkloadsConfigMap(
      request: DeleteUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func saveSnapshot(
      request: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):saveSnapshot"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func loadSnapshot(
      request: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):loadSnapshot"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func databaseFailover(
      request: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):databaseFailover"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func fetchDatabaseProperties(
      request: FetchDatabasePropertiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.environment as Swift.String?, !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding("'request.environment' is not set or is empty")
        }
        return "/v1/\(pathVariable0):fetchDatabaseProperties"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/operations"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(
        contentsOf: try encoder.encode(request.returnPartialSuccess, prefix: "returnPartialSuccess")
      )
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
