// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration information for an environment.
public struct EnvironmentConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The Kubernetes Engine cluster used to run this environment.
  public var gkeCluster: Swift.String = Swift.String()

  /// Output only. The Cloud Storage prefix of the DAGs for this environment.
  /// Although Cloud Storage objects reside in a flat namespace, a hierarchical
  /// file tree can be simulated using "/"-delimited object name prefixes. DAG
  /// objects for this environment reside in a simulated directory with the given
  /// prefix.
  public var dagGcsPrefix: Swift.String = Swift.String()

  /// The number of nodes in the Kubernetes Engine cluster that will be
  /// used to run this environment.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var nodeCount: Swift.Int32 = Swift.Int32()

  /// Optional. The configuration settings for software inside the environment.
  public var softwareConfig: SoftwareConfig? = nil

  /// Optional. The configuration used for the Kubernetes Engine cluster.
  public var nodeConfig: NodeConfig? = nil

  /// Optional. The configuration used for the Private IP Cloud Composer
  /// environment.
  public var privateEnvironmentConfig: PrivateEnvironmentConfig? = nil

  /// Optional. The network-level access control policy for the Airflow web
  /// server. If unspecified, no network-level access restrictions will be
  /// applied.
  public var webServerNetworkAccessControl: WebServerNetworkAccessControl? = nil

  /// Optional. The configuration settings for Cloud SQL instance used internally
  /// by Apache Airflow software.
  public var databaseConfig: DatabaseConfig? = nil

  /// Optional. The configuration settings for the Airflow web server App Engine
  /// instance.
  public var webServerConfig: WebServerConfig? = nil

  /// Optional. The encryption options for the Cloud Composer environment
  /// and its dependencies. Cannot be updated.
  public var encryptionConfig: EncryptionConfig? = nil

  /// Optional. The maintenance window is the period when Cloud Composer
  /// components may undergo maintenance. It is defined so that maintenance is
  /// not executed during peak hours or critical time periods.
  ///
  /// The system will not be under maintenance for every occurrence of this
  /// window, but when maintenance is planned, it will be scheduled
  /// during the window.
  ///
  /// The maintenance window period must encompass at least 12 hours per week.
  /// This may be split into multiple chunks, each with a size of
  /// at least 4 hours.
  ///
  /// If this value is omitted, the default value for maintenance window is
  /// applied. By default, maintenance windows are from 00:00:00 to 04:00:00
  /// (GMT) on Friday, Saturday, and Sunday every week.
  public var maintenanceWindow: MaintenanceWindow? = nil

  /// Optional. The workloads configuration settings for the GKE cluster
  /// associated with the Cloud Composer environment. The GKE cluster runs
  /// Airflow scheduler, web server and workers workloads.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  public var workloadsConfig: WorkloadsConfig? = nil

  /// Optional. The size of the Cloud Composer environment.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  public var environmentSize: EnvironmentConfig.EnvironmentSize =
    EnvironmentConfig.EnvironmentSize()

  /// Output only. The URI of the Apache Airflow Web UI hosted within this
  /// environment (see [Airflow web
  /// interface](/composer/docs/how-to/accessing/airflow-web-interface)).
  public var airflowUri: Swift.String = Swift.String()

  /// Output only. The 'bring your own identity' variant of the URI of the Apache
  /// Airflow Web UI hosted within this environment, to be accessed with external
  /// identities using workforce identity federation (see [Access environments
  /// with workforce identity
  /// federation](/composer/docs/composer-2/access-environments-with-workforce-identity-federation)).
  public var airflowByoidUri: Swift.String = Swift.String()

  /// Optional. The configuration options for GKE cluster master authorized
  /// networks. By default master authorized networks feature is:
  /// - in case of private environment: enabled with no external networks
  /// allowlisted.
  /// - in case of public environment: disabled.
  public var masterAuthorizedNetworksConfig: MasterAuthorizedNetworksConfig? = nil

  /// Optional. The Recovery settings configuration of an environment.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  public var recoveryConfig: RecoveryConfig? = nil

  /// Optional. Resilience mode of the Cloud Composer Environment.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.2.0-airflow-*.*.* and newer.
  public var resilienceMode: EnvironmentConfig.ResilienceMode = EnvironmentConfig.ResilienceMode()

  /// Optional. The configuration setting for Airflow database data retention
  /// mechanism.
  public var dataRetentionConfig: DataRetentionConfig? = nil

  /// Initialize a new instance of `EnvironmentConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EnvironmentConfig().with { $0.gkeCluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The size of the Cloud Composer environment.
  public enum EnvironmentSize: Codable, Equatable, Sendable {
    /// The size of the environment is unspecified.
    case unspecified
    /// The environment size is small.
    case small
    /// The environment size is medium.
    case medium
    /// The environment size is large.
    case large
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .small: return 1
      case .medium: return 2
      case .large: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENVIRONMENT_SIZE_UNSPECIFIED"
      case .small: return "ENVIRONMENT_SIZE_SMALL"
      case .medium: return "ENVIRONMENT_SIZE_MEDIUM"
      case .large: return "ENVIRONMENT_SIZE_LARGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EnvironmentSize/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENVIRONMENT_SIZE_UNSPECIFIED": self = .unspecified
      case "ENVIRONMENT_SIZE_SMALL": self = .small
      case "ENVIRONMENT_SIZE_MEDIUM": self = .medium
      case "ENVIRONMENT_SIZE_LARGE": self = .large
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EnvironmentSize/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .small
      case 2: self = .medium
      case 3: self = .large
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .small: return try container.encode(1)
      case .medium: return try container.encode(2)
      case .large: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Resilience mode of the Cloud Composer Environment.
  public enum ResilienceMode: Codable, Equatable, Sendable {
    /// Default mode doesn't change environment parameters.
    case unspecified
    /// Enabled High Resilience mode, including Cloud SQL HA.
    case highResilience
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .highResilience: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESILIENCE_MODE_UNSPECIFIED"
      case .highResilience: return "HIGH_RESILIENCE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResilienceMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESILIENCE_MODE_UNSPECIFIED": self = .unspecified
      case "HIGH_RESILIENCE": self = .highResilience
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResilienceMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .highResilience
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .highResilience: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.EnvironmentConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
