// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Managed Apache Airflow Environments.
///
/// @Snippet(path: "EnvironmentsQuickstart")
public final class EnvironmentsClient: Clients.EnvironmentsProtocol, Sendable {
  let inner: any Clients.EnvironmentsStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `EnvironmentsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.EnvironmentsStub = try Clients.EnvironmentsTransport(options)
    inner = Clients.EnvironmentsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.EnvironmentsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Create a new environment.
  ///
  /// @Snippet(path: "Environments_CreateEnvironment")
  public func createEnvironment(
    request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createEnvironment(request: request, options: options)
  }

  /// Create a new environment.
  ///
  /// @Snippet(path: "Environments_CreateEnvironment")
  public func createEnvironment(
    withPolling: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
      return try op._extractStatus(Environment.self)
    }
    let rawOp = try await self.createEnvironment(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Get an existing environment.
  ///
  /// @Snippet(path: "Environments_GetEnvironment")
  public func getEnvironment(
    request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
    try await self.inner.getEnvironment(request: request, options: options)
  }

  /// List environments.
  ///
  /// @Snippet(path: "Environments_ListEnvironments")
  public func listEnvironments(
    request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse {
    try await self.inner.listEnvironments(request: request, options: options)
  }

  /// List environments.
  ///
  /// @Snippet(path: "Environments_ListEnvironments")
  public func listEnvironments(
    byItem: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Environment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEnvironments(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Update an environment.
  ///
  /// @Snippet(path: "Environments_UpdateEnvironment")
  public func updateEnvironment(
    request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateEnvironment(request: request, options: options)
  }

  /// Update an environment.
  ///
  /// @Snippet(path: "Environments_UpdateEnvironment")
  public func updateEnvironment(
    withPolling: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
      return try op._extractStatus(Environment.self)
    }
    let rawOp = try await self.updateEnvironment(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Delete an environment.
  ///
  /// @Snippet(path: "Environments_DeleteEnvironment")
  public func deleteEnvironment(
    request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteEnvironment(request: request, options: options)
  }

  /// Delete an environment.
  ///
  /// @Snippet(path: "Environments_DeleteEnvironment")
  public func deleteEnvironment(
    withPolling: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteEnvironment(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Executes Airflow CLI command.
  ///
  /// @Snippet(path: "Environments_ExecuteAirflowCommand")
  public func executeAirflowCommand(
    request: ExecuteAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse {
    try await self.inner.executeAirflowCommand(request: request, options: options)
  }

  /// Stops Airflow CLI command execution.
  ///
  /// @Snippet(path: "Environments_StopAirflowCommand")
  public func stopAirflowCommand(
    request: StopAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse {
    try await self.inner.stopAirflowCommand(request: request, options: options)
  }

  /// Polls Airflow CLI command execution and fetches logs.
  ///
  /// @Snippet(path: "Environments_PollAirflowCommand")
  public func pollAirflowCommand(
    request: PollAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse {
    try await self.inner.pollAirflowCommand(request: request, options: options)
  }

  /// Lists workloads in a Cloud Composer environment. Workload is a unit that
  /// runs a single Composer component.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  ///
  /// @Snippet(path: "Environments_ListWorkloads")
  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse {
    try await self.inner.listWorkloads(request: request, options: options)
  }

  /// Lists workloads in a Cloud Composer environment. Workload is a unit that
  /// runs a single Composer component.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  ///
  /// @Snippet(path: "Environments_ListWorkloads")
  public func listWorkloads(
    byItem: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkloads(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Check if an upgrade operation on the environment will succeed.
  ///
  /// In case of problems detailed info can be found in the returned Operation.
  ///
  /// @Snippet(path: "Environments_CheckUpgrade")
  public func checkUpgrade(
    request: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.checkUpgrade(request: request, options: options)
  }

  /// Check if an upgrade operation on the environment will succeed.
  ///
  /// In case of problems detailed info can be found in the returned Operation.
  ///
  /// @Snippet(path: "Environments_CheckUpgrade")
  public func checkUpgrade(
    withPolling: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CheckUpgradeResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<CheckUpgradeResponse>.State in
      return try op._extractStatus(CheckUpgradeResponse.self)
    }
    let rawOp = try await self.checkUpgrade(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<CheckUpgradeResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a user workloads Secret.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_CreateUserWorkloadsSecret")
  public func createUserWorkloadsSecret(
    request: CreateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    try await self.inner.createUserWorkloadsSecret(request: request, options: options)
  }

  /// Gets an existing user workloads Secret.
  /// Values of the "data" field in the response are cleared.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_GetUserWorkloadsSecret")
  public func getUserWorkloadsSecret(
    request: GetUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    try await self.inner.getUserWorkloadsSecret(request: request, options: options)
  }

  /// Lists user workloads Secrets.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsSecrets")
  public func listUserWorkloadsSecrets(
    request: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse {
    try await self.inner.listUserWorkloadsSecrets(request: request, options: options)
  }

  /// Lists user workloads Secrets.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsSecrets")
  public func listUserWorkloadsSecrets(
    byItem: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<UserWorkloadsSecret, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listUserWorkloadsSecrets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Updates a user workloads Secret.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_UpdateUserWorkloadsSecret")
  public func updateUserWorkloadsSecret(
    request: UpdateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    try await self.inner.updateUserWorkloadsSecret(request: request, options: options)
  }

  /// Deletes a user workloads Secret.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_DeleteUserWorkloadsSecret")
  public func deleteUserWorkloadsSecret(
    request: DeleteUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteUserWorkloadsSecret(request: request, options: options)
  }

  /// Creates a user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_CreateUserWorkloadsConfigMap")
  public func createUserWorkloadsConfigMap(
    request: CreateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    try await self.inner.createUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Gets an existing user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_GetUserWorkloadsConfigMap")
  public func getUserWorkloadsConfigMap(
    request: GetUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    try await self.inner.getUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Lists user workloads ConfigMaps.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsConfigMaps")
  public func listUserWorkloadsConfigMaps(
    request: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse {
    try await self.inner.listUserWorkloadsConfigMaps(request: request, options: options)
  }

  /// Lists user workloads ConfigMaps.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsConfigMaps")
  public func listUserWorkloadsConfigMaps(
    byItem: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<UserWorkloadsConfigMap, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listUserWorkloadsConfigMaps(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Updates a user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_UpdateUserWorkloadsConfigMap")
  public func updateUserWorkloadsConfigMap(
    request: UpdateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    try await self.inner.updateUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Deletes a user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_DeleteUserWorkloadsConfigMap")
  public func deleteUserWorkloadsConfigMap(
    request: DeleteUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Creates a snapshots of a Cloud Composer environment.
  ///
  /// As a result of this operation, snapshot of environment's state is stored
  /// in a location specified in the SaveSnapshotRequest.
  ///
  /// @Snippet(path: "Environments_SaveSnapshot")
  public func saveSnapshot(
    request: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.saveSnapshot(request: request, options: options)
  }

  /// Creates a snapshots of a Cloud Composer environment.
  ///
  /// As a result of this operation, snapshot of environment's state is stored
  /// in a location specified in the SaveSnapshotRequest.
  ///
  /// @Snippet(path: "Environments_SaveSnapshot")
  public func saveSnapshot(
    withPolling: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<SaveSnapshotResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<SaveSnapshotResponse>.State in
      return try op._extractStatus(SaveSnapshotResponse.self)
    }
    let rawOp = try await self.saveSnapshot(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<SaveSnapshotResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Loads a snapshot of a Cloud Composer environment.
  ///
  /// As a result of this operation, a snapshot of environment's specified in
  /// LoadSnapshotRequest is loaded into the environment.
  ///
  /// @Snippet(path: "Environments_LoadSnapshot")
  public func loadSnapshot(
    request: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.loadSnapshot(request: request, options: options)
  }

  /// Loads a snapshot of a Cloud Composer environment.
  ///
  /// As a result of this operation, a snapshot of environment's specified in
  /// LoadSnapshotRequest is loaded into the environment.
  ///
  /// @Snippet(path: "Environments_LoadSnapshot")
  public func loadSnapshot(
    withPolling: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LoadSnapshotResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<LoadSnapshotResponse>.State in
      return try op._extractStatus(LoadSnapshotResponse.self)
    }
    let rawOp = try await self.loadSnapshot(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<LoadSnapshotResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Triggers database failover (only for highly resilient environments).
  ///
  /// @Snippet(path: "Environments_DatabaseFailover")
  public func databaseFailover(
    request: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.databaseFailover(request: request, options: options)
  }

  /// Triggers database failover (only for highly resilient environments).
  ///
  /// @Snippet(path: "Environments_DatabaseFailover")
  public func databaseFailover(
    withPolling: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatabaseFailoverResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<DatabaseFailoverResponse>.State in
      return try op._extractStatus(DatabaseFailoverResponse.self)
    }
    let rawOp = try await self.databaseFailover(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<DatabaseFailoverResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Fetches database properties.
  ///
  /// @Snippet(path: "Environments_FetchDatabaseProperties")
  public func fetchDatabaseProperties(
    request: FetchDatabasePropertiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse {
    try await self.inner.fetchDatabaseProperties(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `EnvironmentsClient`.
  ///
  /// To mock `EnvironmentsClient` change your functions to receive
  /// `some EnvironmentsProtocol` or `any EnvironmentsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol EnvironmentsProtocol {
    /// See `EnvironmentsClient.createEnvironment`.
    func createEnvironment(request: CreateEnvironmentRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.createEnvironment`.
    func createEnvironment(withPolling: CreateEnvironmentRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Environment>

    /// See `EnvironmentsClient.createEnvironment`.
    func createEnvironment(
      parent: Swift.String,
      environment: Environment?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

    /// See `EnvironmentsClient.getEnvironment`.
    func getEnvironment(request: GetEnvironmentRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.Environment

    /// See `EnvironmentsClient.getEnvironment`.
    func getEnvironment(
      name: Swift.String,
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment

    /// See `EnvironmentsClient.listEnvironments`.
    func listEnvironments(request: ListEnvironmentsRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse

    /// See `EnvironmentsClient.listEnvironments`.
    func listEnvironments(
      byItem: ListEnvironmentsRequest
    ) throws -> any AsyncSequence<Environment, Swift.Error>

    /// See `EnvironmentsClient.listEnvironments`.
    func listEnvironments(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Environment, Swift.Error>

    /// See `EnvironmentsClient.updateEnvironment`.
    func updateEnvironment(request: UpdateEnvironmentRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.updateEnvironment`.
    func updateEnvironment(withPolling: UpdateEnvironmentRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Environment>

    /// See `EnvironmentsClient.updateEnvironment`.
    func updateEnvironment(
      name: Swift.String,
      environment: Environment?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

    /// See `EnvironmentsClient.deleteEnvironment`.
    func deleteEnvironment(request: DeleteEnvironmentRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.deleteEnvironment`.
    func deleteEnvironment(withPolling: DeleteEnvironmentRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `EnvironmentsClient.deleteEnvironment`.
    func deleteEnvironment(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `EnvironmentsClient.executeAirflowCommand`.
    func executeAirflowCommand(request: ExecuteAirflowCommandRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse

    /// See `EnvironmentsClient.stopAirflowCommand`.
    func stopAirflowCommand(request: StopAirflowCommandRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse

    /// See `EnvironmentsClient.pollAirflowCommand`.
    func pollAirflowCommand(request: PollAirflowCommandRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse

    /// See `EnvironmentsClient.listWorkloads`.
    func listWorkloads(request: ListWorkloadsRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse

    /// See `EnvironmentsClient.listWorkloads`.
    func listWorkloads(
      byItem: ListWorkloadsRequest
    ) throws -> any AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error>

    /// See `EnvironmentsClient.listWorkloads`.
    func listWorkloads(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error>

    /// See `EnvironmentsClient.checkUpgrade`.
    func checkUpgrade(request: CheckUpgradeRequest) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.checkUpgrade`.
    func checkUpgrade(withPolling: CheckUpgradeRequest) async throws -> any GoogleCloudGax
      .PollableOperation<CheckUpgradeResponse>

    /// See `EnvironmentsClient.createUserWorkloadsSecret`.
    func createUserWorkloadsSecret(request: CreateUserWorkloadsSecretRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.createUserWorkloadsSecret`.
    func createUserWorkloadsSecret(
      parent: Swift.String,
      userWorkloadsSecret: UserWorkloadsSecret?,
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.getUserWorkloadsSecret`.
    func getUserWorkloadsSecret(request: GetUserWorkloadsSecretRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.getUserWorkloadsSecret`.
    func getUserWorkloadsSecret(
      name: Swift.String,
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.listUserWorkloadsSecrets`.
    func listUserWorkloadsSecrets(request: ListUserWorkloadsSecretsRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse

    /// See `EnvironmentsClient.listUserWorkloadsSecrets`.
    func listUserWorkloadsSecrets(
      byItem: ListUserWorkloadsSecretsRequest
    ) throws -> any AsyncSequence<UserWorkloadsSecret, Swift.Error>

    /// See `EnvironmentsClient.listUserWorkloadsSecrets`.
    func listUserWorkloadsSecrets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<UserWorkloadsSecret, Swift.Error>

    /// See `EnvironmentsClient.updateUserWorkloadsSecret`.
    func updateUserWorkloadsSecret(request: UpdateUserWorkloadsSecretRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.updateUserWorkloadsSecret`.
    func updateUserWorkloadsSecret(
      userWorkloadsSecret: UserWorkloadsSecret?,
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.deleteUserWorkloadsSecret`.
    func deleteUserWorkloadsSecret(request: DeleteUserWorkloadsSecretRequest) async throws

    /// See `EnvironmentsClient.deleteUserWorkloadsSecret`.
    func deleteUserWorkloadsSecret(
      name: Swift.String,
    ) async throws

    /// See `EnvironmentsClient.createUserWorkloadsConfigMap`.
    func createUserWorkloadsConfigMap(request: CreateUserWorkloadsConfigMapRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.createUserWorkloadsConfigMap`.
    func createUserWorkloadsConfigMap(
      parent: Swift.String,
      userWorkloadsConfigMap: UserWorkloadsConfigMap?,
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.getUserWorkloadsConfigMap`.
    func getUserWorkloadsConfigMap(request: GetUserWorkloadsConfigMapRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.getUserWorkloadsConfigMap`.
    func getUserWorkloadsConfigMap(
      name: Swift.String,
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.listUserWorkloadsConfigMaps`.
    func listUserWorkloadsConfigMaps(request: ListUserWorkloadsConfigMapsRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse

    /// See `EnvironmentsClient.listUserWorkloadsConfigMaps`.
    func listUserWorkloadsConfigMaps(
      byItem: ListUserWorkloadsConfigMapsRequest
    ) throws -> any AsyncSequence<UserWorkloadsConfigMap, Swift.Error>

    /// See `EnvironmentsClient.listUserWorkloadsConfigMaps`.
    func listUserWorkloadsConfigMaps(
      parent: Swift.String,
    ) throws -> any AsyncSequence<UserWorkloadsConfigMap, Swift.Error>

    /// See `EnvironmentsClient.updateUserWorkloadsConfigMap`.
    func updateUserWorkloadsConfigMap(request: UpdateUserWorkloadsConfigMapRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.updateUserWorkloadsConfigMap`.
    func updateUserWorkloadsConfigMap(
      userWorkloadsConfigMap: UserWorkloadsConfigMap?,
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.deleteUserWorkloadsConfigMap`.
    func deleteUserWorkloadsConfigMap(request: DeleteUserWorkloadsConfigMapRequest) async throws

    /// See `EnvironmentsClient.deleteUserWorkloadsConfigMap`.
    func deleteUserWorkloadsConfigMap(
      name: Swift.String,
    ) async throws

    /// See `EnvironmentsClient.saveSnapshot`.
    func saveSnapshot(request: SaveSnapshotRequest) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.saveSnapshot`.
    func saveSnapshot(withPolling: SaveSnapshotRequest) async throws -> any GoogleCloudGax
      .PollableOperation<SaveSnapshotResponse>

    /// See `EnvironmentsClient.loadSnapshot`.
    func loadSnapshot(request: LoadSnapshotRequest) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.loadSnapshot`.
    func loadSnapshot(withPolling: LoadSnapshotRequest) async throws -> any GoogleCloudGax
      .PollableOperation<LoadSnapshotResponse>

    /// See `EnvironmentsClient.databaseFailover`.
    func databaseFailover(request: DatabaseFailoverRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.databaseFailover`.
    func databaseFailover(withPolling: DatabaseFailoverRequest) async throws -> any GoogleCloudGax
      .PollableOperation<DatabaseFailoverResponse>

    /// See `EnvironmentsClient.fetchDatabaseProperties`.
    func fetchDatabaseProperties(request: FetchDatabasePropertiesRequest) async throws
      -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse

    /// See `EnvironmentsClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `EnvironmentsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `EnvironmentsClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `EnvironmentsClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `EnvironmentsClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `EnvironmentsClient.createEnvironment`.
    func createEnvironment(
      request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.createEnvironment`.
    func createEnvironment(
      withPolling: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

    /// See `EnvironmentsClient.getEnvironment`.
    func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment

    /// See `EnvironmentsClient.listEnvironments`.
    func listEnvironments(
      request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse

    /// See `EnvironmentsClient.listEnvironments`.
    func listEnvironments(
      byItem: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Environment, Swift.Error>

    /// See `EnvironmentsClient.updateEnvironment`.
    func updateEnvironment(
      request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.updateEnvironment`.
    func updateEnvironment(
      withPolling: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

    /// See `EnvironmentsClient.deleteEnvironment`.
    func deleteEnvironment(
      request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.deleteEnvironment`.
    func deleteEnvironment(
      withPolling: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `EnvironmentsClient.executeAirflowCommand`.
    func executeAirflowCommand(
      request: ExecuteAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse

    /// See `EnvironmentsClient.stopAirflowCommand`.
    func stopAirflowCommand(
      request: StopAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse

    /// See `EnvironmentsClient.pollAirflowCommand`.
    func pollAirflowCommand(
      request: PollAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse

    /// See `EnvironmentsClient.listWorkloads`.
    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse

    /// See `EnvironmentsClient.listWorkloads`.
    func listWorkloads(
      byItem: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error>

    /// See `EnvironmentsClient.checkUpgrade`.
    func checkUpgrade(
      request: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.checkUpgrade`.
    func checkUpgrade(
      withPolling: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<CheckUpgradeResponse>

    /// See `EnvironmentsClient.createUserWorkloadsSecret`.
    func createUserWorkloadsSecret(
      request: CreateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.getUserWorkloadsSecret`.
    func getUserWorkloadsSecret(
      request: GetUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.listUserWorkloadsSecrets`.
    func listUserWorkloadsSecrets(
      request: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse

    /// See `EnvironmentsClient.listUserWorkloadsSecrets`.
    func listUserWorkloadsSecrets(
      byItem: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<UserWorkloadsSecret, Swift.Error>

    /// See `EnvironmentsClient.updateUserWorkloadsSecret`.
    func updateUserWorkloadsSecret(
      request: UpdateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.deleteUserWorkloadsSecret`.
    func deleteUserWorkloadsSecret(
      request: DeleteUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `EnvironmentsClient.createUserWorkloadsConfigMap`.
    func createUserWorkloadsConfigMap(
      request: CreateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.getUserWorkloadsConfigMap`.
    func getUserWorkloadsConfigMap(
      request: GetUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.listUserWorkloadsConfigMaps`.
    func listUserWorkloadsConfigMaps(
      request: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse

    /// See `EnvironmentsClient.listUserWorkloadsConfigMaps`.
    func listUserWorkloadsConfigMaps(
      byItem: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<UserWorkloadsConfigMap, Swift.Error>

    /// See `EnvironmentsClient.updateUserWorkloadsConfigMap`.
    func updateUserWorkloadsConfigMap(
      request: UpdateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.deleteUserWorkloadsConfigMap`.
    func deleteUserWorkloadsConfigMap(
      request: DeleteUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `EnvironmentsClient.saveSnapshot`.
    func saveSnapshot(
      request: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.saveSnapshot`.
    func saveSnapshot(
      withPolling: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<SaveSnapshotResponse>

    /// See `EnvironmentsClient.loadSnapshot`.
    func loadSnapshot(
      request: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.loadSnapshot`.
    func loadSnapshot(
      withPolling: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<LoadSnapshotResponse>

    /// See `EnvironmentsClient.databaseFailover`.
    func databaseFailover(
      request: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.databaseFailover`.
    func databaseFailover(
      withPolling: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DatabaseFailoverResponse>

    /// See `EnvironmentsClient.fetchDatabaseProperties`.
    func fetchDatabaseProperties(
      request: FetchDatabasePropertiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse

    /// See `EnvironmentsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `EnvironmentsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `EnvironmentsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.EnvironmentsProtocol {
  public func createEnvironment(request: CreateEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createEnvironment(request: request, options: .init())
  }

  public func createEnvironment(
    request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createEnvironment(withPolling: CreateEnvironmentRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Environment>
  {
    try await self.createEnvironment(withPolling: withPolling, options: .init())
  }

  public func createEnvironment(
    withPolling: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createEnvironment(
    parent: Swift.String,
    environment: Environment?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
    let request = CreateEnvironmentRequest().with {
      $0.parent = parent
      $0.environment = environment
    }
    return try await self.createEnvironment(withPolling: request)
  }

  public func getEnvironment(request: GetEnvironmentRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.Environment
  {
    try await self.getEnvironment(request: request, options: .init())
  }

  public func getEnvironment(
    request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEnvironment(
    name: Swift.String,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
    let request = GetEnvironmentRequest().with {
      $0.name = name
    }
    return try await self.getEnvironment(request: request)
  }

  public func listEnvironments(request: ListEnvironmentsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse
  {
    try await self.listEnvironments(request: request, options: .init())
  }

  public func listEnvironments(
    request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEnvironments(
    byItem: ListEnvironmentsRequest
  ) throws -> any AsyncSequence<Environment, Swift.Error> {
    try self.listEnvironments(byItem: byItem, options: .init())
  }

  public func listEnvironments(
    byItem: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Environment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEnvironments(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Environment, Swift.Error> {
    let request = ListEnvironmentsRequest().with {
      $0.parent = parent
    }
    return try self.listEnvironments(byItem: request)
  }

  public func updateEnvironment(request: UpdateEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateEnvironment(request: request, options: .init())
  }

  public func updateEnvironment(
    request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateEnvironment(withPolling: UpdateEnvironmentRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Environment>
  {
    try await self.updateEnvironment(withPolling: withPolling, options: .init())
  }

  public func updateEnvironment(
    withPolling: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateEnvironment(
    name: Swift.String,
    environment: Environment?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
    let request = UpdateEnvironmentRequest().with {
      $0.name = name
      $0.environment = environment
      $0.updateMask = updateMask
    }
    return try await self.updateEnvironment(withPolling: request)
  }

  public func deleteEnvironment(request: DeleteEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteEnvironment(request: request, options: .init())
  }

  public func deleteEnvironment(
    request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteEnvironment(withPolling: DeleteEnvironmentRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteEnvironment(withPolling: withPolling, options: .init())
  }

  public func deleteEnvironment(
    withPolling: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteEnvironment(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteEnvironmentRequest().with {
      $0.name = name
    }
    return try await self.deleteEnvironment(withPolling: request)
  }

  public func executeAirflowCommand(request: ExecuteAirflowCommandRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse
  {
    try await self.executeAirflowCommand(request: request, options: .init())
  }

  public func executeAirflowCommand(
    request: ExecuteAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func stopAirflowCommand(request: StopAirflowCommandRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse
  {
    try await self.stopAirflowCommand(request: request, options: .init())
  }

  public func stopAirflowCommand(
    request: StopAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func pollAirflowCommand(request: PollAirflowCommandRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse
  {
    try await self.pollAirflowCommand(request: request, options: .init())
  }

  public func pollAirflowCommand(
    request: PollAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkloads(request: ListWorkloadsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse
  {
    try await self.listWorkloads(request: request, options: .init())
  }

  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkloads(
    byItem: ListWorkloadsRequest
  ) throws -> any AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error> {
    try self.listWorkloads(byItem: byItem, options: .init())
  }

  public func listWorkloads(
    byItem: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkloads(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error> {
    let request = ListWorkloadsRequest().with {
      $0.parent = parent
    }
    return try self.listWorkloads(byItem: request)
  }

  public func checkUpgrade(request: CheckUpgradeRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.checkUpgrade(request: request, options: .init())
  }

  public func checkUpgrade(
    request: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func checkUpgrade(withPolling: CheckUpgradeRequest) async throws -> any GoogleCloudGax
    .PollableOperation<CheckUpgradeResponse>
  {
    try await self.checkUpgrade(withPolling: withPolling, options: .init())
  }

  public func checkUpgrade(
    withPolling: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CheckUpgradeResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<CheckUpgradeResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createUserWorkloadsSecret(request: CreateUserWorkloadsSecretRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
  {
    try await self.createUserWorkloadsSecret(request: request, options: .init())
  }

  public func createUserWorkloadsSecret(
    request: CreateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createUserWorkloadsSecret(
    parent: Swift.String,
    userWorkloadsSecret: UserWorkloadsSecret?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    let request = CreateUserWorkloadsSecretRequest().with {
      $0.parent = parent
      $0.userWorkloadsSecret = userWorkloadsSecret
    }
    return try await self.createUserWorkloadsSecret(request: request)
  }

  public func getUserWorkloadsSecret(request: GetUserWorkloadsSecretRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
  {
    try await self.getUserWorkloadsSecret(request: request, options: .init())
  }

  public func getUserWorkloadsSecret(
    request: GetUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getUserWorkloadsSecret(
    name: Swift.String,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    let request = GetUserWorkloadsSecretRequest().with {
      $0.name = name
    }
    return try await self.getUserWorkloadsSecret(request: request)
  }

  public func listUserWorkloadsSecrets(request: ListUserWorkloadsSecretsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse
  {
    try await self.listUserWorkloadsSecrets(request: request, options: .init())
  }

  public func listUserWorkloadsSecrets(
    request: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listUserWorkloadsSecrets(
    byItem: ListUserWorkloadsSecretsRequest
  ) throws -> any AsyncSequence<UserWorkloadsSecret, Swift.Error> {
    try self.listUserWorkloadsSecrets(byItem: byItem, options: .init())
  }

  public func listUserWorkloadsSecrets(
    byItem: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<UserWorkloadsSecret, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUserWorkloadsSecrets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<UserWorkloadsSecret, Swift.Error> {
    let request = ListUserWorkloadsSecretsRequest().with {
      $0.parent = parent
    }
    return try self.listUserWorkloadsSecrets(byItem: request)
  }

  public func updateUserWorkloadsSecret(request: UpdateUserWorkloadsSecretRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
  {
    try await self.updateUserWorkloadsSecret(request: request, options: .init())
  }

  public func updateUserWorkloadsSecret(
    request: UpdateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateUserWorkloadsSecret(
    userWorkloadsSecret: UserWorkloadsSecret?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    let request = UpdateUserWorkloadsSecretRequest().with {
      $0.userWorkloadsSecret = userWorkloadsSecret
    }
    return try await self.updateUserWorkloadsSecret(request: request)
  }

  public func deleteUserWorkloadsSecret(request: DeleteUserWorkloadsSecretRequest) async throws {
    try await self.deleteUserWorkloadsSecret(request: request, options: .init())
  }

  public func deleteUserWorkloadsSecret(
    request: DeleteUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteUserWorkloadsSecret(
    name: Swift.String,
  ) async throws {
    let request = DeleteUserWorkloadsSecretRequest().with {
      $0.name = name
    }
    try await self.deleteUserWorkloadsSecret(request: request)
  }

  public func createUserWorkloadsConfigMap(request: CreateUserWorkloadsConfigMapRequest)
    async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
  {
    try await self.createUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func createUserWorkloadsConfigMap(
    request: CreateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createUserWorkloadsConfigMap(
    parent: Swift.String,
    userWorkloadsConfigMap: UserWorkloadsConfigMap?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    let request = CreateUserWorkloadsConfigMapRequest().with {
      $0.parent = parent
      $0.userWorkloadsConfigMap = userWorkloadsConfigMap
    }
    return try await self.createUserWorkloadsConfigMap(request: request)
  }

  public func getUserWorkloadsConfigMap(request: GetUserWorkloadsConfigMapRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
  {
    try await self.getUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func getUserWorkloadsConfigMap(
    request: GetUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getUserWorkloadsConfigMap(
    name: Swift.String,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    let request = GetUserWorkloadsConfigMapRequest().with {
      $0.name = name
    }
    return try await self.getUserWorkloadsConfigMap(request: request)
  }

  public func listUserWorkloadsConfigMaps(request: ListUserWorkloadsConfigMapsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse
  {
    try await self.listUserWorkloadsConfigMaps(request: request, options: .init())
  }

  public func listUserWorkloadsConfigMaps(
    request: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listUserWorkloadsConfigMaps(
    byItem: ListUserWorkloadsConfigMapsRequest
  ) throws -> any AsyncSequence<UserWorkloadsConfigMap, Swift.Error> {
    try self.listUserWorkloadsConfigMaps(byItem: byItem, options: .init())
  }

  public func listUserWorkloadsConfigMaps(
    byItem: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<UserWorkloadsConfigMap, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUserWorkloadsConfigMaps(
    parent: Swift.String,
  ) throws -> any AsyncSequence<UserWorkloadsConfigMap, Swift.Error> {
    let request = ListUserWorkloadsConfigMapsRequest().with {
      $0.parent = parent
    }
    return try self.listUserWorkloadsConfigMaps(byItem: request)
  }

  public func updateUserWorkloadsConfigMap(request: UpdateUserWorkloadsConfigMapRequest)
    async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
  {
    try await self.updateUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func updateUserWorkloadsConfigMap(
    request: UpdateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateUserWorkloadsConfigMap(
    userWorkloadsConfigMap: UserWorkloadsConfigMap?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    let request = UpdateUserWorkloadsConfigMapRequest().with {
      $0.userWorkloadsConfigMap = userWorkloadsConfigMap
    }
    return try await self.updateUserWorkloadsConfigMap(request: request)
  }

  public func deleteUserWorkloadsConfigMap(request: DeleteUserWorkloadsConfigMapRequest)
    async throws
  {
    try await self.deleteUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func deleteUserWorkloadsConfigMap(
    request: DeleteUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteUserWorkloadsConfigMap(
    name: Swift.String,
  ) async throws {
    let request = DeleteUserWorkloadsConfigMapRequest().with {
      $0.name = name
    }
    try await self.deleteUserWorkloadsConfigMap(request: request)
  }

  public func saveSnapshot(request: SaveSnapshotRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.saveSnapshot(request: request, options: .init())
  }

  public func saveSnapshot(
    request: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func saveSnapshot(withPolling: SaveSnapshotRequest) async throws -> any GoogleCloudGax
    .PollableOperation<SaveSnapshotResponse>
  {
    try await self.saveSnapshot(withPolling: withPolling, options: .init())
  }

  public func saveSnapshot(
    withPolling: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<SaveSnapshotResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<SaveSnapshotResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func loadSnapshot(request: LoadSnapshotRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.loadSnapshot(request: request, options: .init())
  }

  public func loadSnapshot(
    request: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func loadSnapshot(withPolling: LoadSnapshotRequest) async throws -> any GoogleCloudGax
    .PollableOperation<LoadSnapshotResponse>
  {
    try await self.loadSnapshot(withPolling: withPolling, options: .init())
  }

  public func loadSnapshot(
    withPolling: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LoadSnapshotResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<LoadSnapshotResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func databaseFailover(request: DatabaseFailoverRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.databaseFailover(request: request, options: .init())
  }

  public func databaseFailover(
    request: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func databaseFailover(withPolling: DatabaseFailoverRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DatabaseFailoverResponse>
  {
    try await self.databaseFailover(withPolling: withPolling, options: .init())
  }

  public func databaseFailover(
    withPolling: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatabaseFailoverResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<DatabaseFailoverResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func fetchDatabaseProperties(request: FetchDatabasePropertiesRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse
  {
    try await self.fetchDatabaseProperties(request: request, options: .init())
  }

  public func fetchDatabaseProperties(
    request: FetchDatabasePropertiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }
}
