// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class EnvironmentsRetry: EnvironmentsStub {
    let inner: any EnvironmentsStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any EnvironmentsStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createEnvironment(
      request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateEnvironmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createEnvironment(request: r, options: o)
        })
    }

    public func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEnvironmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.Environment
          in
          return try await self.inner.getEnvironment(request: r, options: o)
        })
    }

    public func listEnvironments(
      request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEnvironmentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse
          in
          return try await self.inner.listEnvironments(request: r, options: o)
        })
    }

    public func updateEnvironment(
      request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateEnvironmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateEnvironment(request: r, options: o)
        })
    }

    public func deleteEnvironment(
      request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteEnvironmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteEnvironment(request: r, options: o)
        })
    }

    public func executeAirflowCommand(
      request: ExecuteAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExecuteAirflowCommandRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse
          in
          return try await self.inner.executeAirflowCommand(request: r, options: o)
        })
    }

    public func stopAirflowCommand(
      request: StopAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopAirflowCommandRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse
          in
          return try await self.inner.stopAirflowCommand(request: r, options: o)
        })
    }

    public func pollAirflowCommand(
      request: PollAirflowCommandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PollAirflowCommandRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse
          in
          return try await self.inner.pollAirflowCommand(request: r, options: o)
        })
    }

    public func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListWorkloadsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse
          in
          return try await self.inner.listWorkloads(request: r, options: o)
        })
    }

    public func checkUpgrade(
      request: CheckUpgradeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CheckUpgradeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.checkUpgrade(request: r, options: o)
        })
    }

    public func createUserWorkloadsSecret(
      request: CreateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateUserWorkloadsSecretRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
          in
          return try await self.inner.createUserWorkloadsSecret(request: r, options: o)
        })
    }

    public func getUserWorkloadsSecret(
      request: GetUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetUserWorkloadsSecretRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
          in
          return try await self.inner.getUserWorkloadsSecret(request: r, options: o)
        })
    }

    public func listUserWorkloadsSecrets(
      request: ListUserWorkloadsSecretsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListUserWorkloadsSecretsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse
          in
          return try await self.inner.listUserWorkloadsSecrets(request: r, options: o)
        })
    }

    public func updateUserWorkloadsSecret(
      request: UpdateUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: UpdateUserWorkloadsSecretRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
          in
          return try await self.inner.updateUserWorkloadsSecret(request: r, options: o)
        })
    }

    public func deleteUserWorkloadsSecret(
      request: DeleteUserWorkloadsSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteUserWorkloadsSecretRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteUserWorkloadsSecret(request: r, options: o)
        })
    }

    public func createUserWorkloadsConfigMap(
      request: CreateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateUserWorkloadsConfigMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
          in
          return try await self.inner.createUserWorkloadsConfigMap(request: r, options: o)
        })
    }

    public func getUserWorkloadsConfigMap(
      request: GetUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetUserWorkloadsConfigMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
          in
          return try await self.inner.getUserWorkloadsConfigMap(request: r, options: o)
        })
    }

    public func listUserWorkloadsConfigMaps(
      request: ListUserWorkloadsConfigMapsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListUserWorkloadsConfigMapsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse
          in
          return try await self.inner.listUserWorkloadsConfigMaps(request: r, options: o)
        })
    }

    public func updateUserWorkloadsConfigMap(
      request: UpdateUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: UpdateUserWorkloadsConfigMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
          in
          return try await self.inner.updateUserWorkloadsConfigMap(request: r, options: o)
        })
    }

    public func deleteUserWorkloadsConfigMap(
      request: DeleteUserWorkloadsConfigMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteUserWorkloadsConfigMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteUserWorkloadsConfigMap(request: r, options: o)
        })
    }

    public func saveSnapshot(
      request: SaveSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SaveSnapshotRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.saveSnapshot(request: r, options: o)
        })
    }

    public func loadSnapshot(
      request: LoadSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: LoadSnapshotRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.loadSnapshot(request: r, options: o)
        })
    }

    public func databaseFailover(
      request: DatabaseFailoverRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DatabaseFailoverRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.databaseFailover(request: r, options: o)
        })
    }

    public func fetchDatabaseProperties(
      request: FetchDatabasePropertiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchDatabasePropertiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse
          in
          return try await self.inner.fetchDatabaseProperties(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }
  }
}
