// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol EnvironmentsStub: Sendable {
    func createEnvironment(
      request: CreateEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment

    func listEnvironments(
      request: ListEnvironmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse

    func updateEnvironment(
      request: UpdateEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEnvironment(
      request: DeleteEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func executeAirflowCommand(
      request: ExecuteAirflowCommandRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse

    func stopAirflowCommand(
      request: StopAirflowCommandRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse

    func pollAirflowCommand(
      request: PollAirflowCommandRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse

    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse

    func checkUpgrade(
      request: CheckUpgradeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createUserWorkloadsSecret(
      request: CreateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    func getUserWorkloadsSecret(
      request: GetUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    func listUserWorkloadsSecrets(
      request: ListUserWorkloadsSecretsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse

    func updateUserWorkloadsSecret(
      request: UpdateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    func deleteUserWorkloadsSecret(
      request: DeleteUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws

    func createUserWorkloadsConfigMap(
      request: CreateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    func getUserWorkloadsConfigMap(
      request: GetUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    func listUserWorkloadsConfigMaps(
      request: ListUserWorkloadsConfigMapsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse

    func updateUserWorkloadsConfigMap(
      request: UpdateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    func deleteUserWorkloadsConfigMap(
      request: DeleteUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws

    func saveSnapshot(
      request: SaveSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func loadSnapshot(
      request: LoadSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func databaseFailover(
      request: DatabaseFailoverRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func fetchDatabaseProperties(
      request: FetchDatabasePropertiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
