// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Response to ListWorkloadsRequest.
public struct ListWorkloadsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The list of environment workloads.
  public var workloads: [ListWorkloadsResponse.ComposerWorkload] = []

  /// The page token used to query for the next page if one exists.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListWorkloadsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListWorkloadsResponse().with { $0.workloads = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information about a single workload.
  public struct ComposerWorkload: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of a workload.
    public var name: Swift.String = Swift.String()

    /// Type of a workload.
    public var type: ListWorkloadsResponse.ComposerWorkloadType =
      ListWorkloadsResponse.ComposerWorkloadType()

    /// Output only. Status of a workload.
    public var status: ListWorkloadsResponse.ComposerWorkloadStatus? = nil

    /// Initialize a new instance of `ComposerWorkload`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ComposerWorkload().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkload"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Workload status.
  public struct ComposerWorkloadStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Workload state.
    public var state: ListWorkloadsResponse.ComposerWorkloadState =
      ListWorkloadsResponse.ComposerWorkloadState()

    /// Output only. Text to provide more descriptive status.
    public var statusMessage: Swift.String = Swift.String()

    /// Output only. Detailed message of the status.
    public var detailedStatusMessage: Swift.String = Swift.String()

    /// Initialize a new instance of `ComposerWorkloadStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ComposerWorkloadStatus().with { $0.state = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadStatus"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Supported workload types.
  public enum ComposerWorkloadType: Codable, Equatable, Sendable {
    /// Not able to determine the type of the workload.
    case unspecified
    /// Celery worker.
    case celeryWorker
    /// Kubernetes worker.
    case kubernetesWorker
    /// Workload created by Kubernetes Pod Operator.
    case kubernetesOperatorPod
    /// Airflow scheduler.
    case scheduler
    /// Airflow Dag processor.
    case dagProcessor
    /// Airflow triggerer.
    case triggerer
    /// Airflow web server UI.
    case webServer
    /// Redis.
    case redis
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .celeryWorker: return 1
      case .kubernetesWorker: return 2
      case .kubernetesOperatorPod: return 3
      case .scheduler: return 4
      case .dagProcessor: return 5
      case .triggerer: return 6
      case .webServer: return 7
      case .redis: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMPOSER_WORKLOAD_TYPE_UNSPECIFIED"
      case .celeryWorker: return "CELERY_WORKER"
      case .kubernetesWorker: return "KUBERNETES_WORKER"
      case .kubernetesOperatorPod: return "KUBERNETES_OPERATOR_POD"
      case .scheduler: return "SCHEDULER"
      case .dagProcessor: return "DAG_PROCESSOR"
      case .triggerer: return "TRIGGERER"
      case .webServer: return "WEB_SERVER"
      case .redis: return "REDIS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComposerWorkloadType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMPOSER_WORKLOAD_TYPE_UNSPECIFIED": self = .unspecified
      case "CELERY_WORKER": self = .celeryWorker
      case "KUBERNETES_WORKER": self = .kubernetesWorker
      case "KUBERNETES_OPERATOR_POD": self = .kubernetesOperatorPod
      case "SCHEDULER": self = .scheduler
      case "DAG_PROCESSOR": self = .dagProcessor
      case "TRIGGERER": self = .triggerer
      case "WEB_SERVER": self = .webServer
      case "REDIS": self = .redis
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComposerWorkloadType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .celeryWorker
      case 2: self = .kubernetesWorker
      case 3: self = .kubernetesOperatorPod
      case 4: self = .scheduler
      case 5: self = .dagProcessor
      case 6: self = .triggerer
      case 7: self = .webServer
      case 8: self = .redis
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .celeryWorker: return try container.encode(1)
      case .kubernetesWorker: return try container.encode(2)
      case .kubernetesOperatorPod: return try container.encode(3)
      case .scheduler: return try container.encode(4)
      case .dagProcessor: return try container.encode(5)
      case .triggerer: return try container.encode(6)
      case .webServer: return try container.encode(7)
      case .redis: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Workload states.
  public enum ComposerWorkloadState: Codable, Equatable, Sendable {
    /// Not able to determine the status of the workload.
    case unspecified
    /// Workload is in pending state and has not yet started.
    case pending
    /// Workload is running fine.
    case ok
    /// Workload is running but there are some non-critical problems.
    case warning
    /// Workload is not running due to an error.
    case error
    /// Workload has finished execution with success.
    case succeeded
    /// Workload has finished execution with failure.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .ok: return 2
      case .warning: return 3
      case .error: return 4
      case .succeeded: return 5
      case .failed: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMPOSER_WORKLOAD_STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .ok: return "OK"
      case .warning: return "WARNING"
      case .error: return "ERROR"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComposerWorkloadState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMPOSER_WORKLOAD_STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "OK": self = .ok
      case "WARNING": self = .warning
      case "ERROR": self = .error
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComposerWorkloadState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .ok
      case 3: self = .warning
      case 4: self = .error
      case 5: self = .succeeded
      case 6: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .ok: return try container.encode(2)
      case .warning: return try container.encode(3)
      case .error: return try container.encode(4)
      case .succeeded: return try container.encode(5)
      case .failed: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [ListWorkloadsResponse.ComposerWorkload] {
    return self.workloads
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
