// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request to load a snapshot into a Cloud Composer environment.
public struct LoadSnapshotRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the target environment in the form:
  /// "projects/{projectId}/locations/{locationId}/environments/{environmentId}"
  public var environment: Swift.String = Swift.String()

  /// A Cloud Storage path to a snapshot to load, e.g.:
  /// "gs://my-bucket/snapshots/project_location_environment_timestamp".
  public var snapshotPath: Swift.String = Swift.String()

  /// Whether or not to skip installing Pypi packages when loading the
  /// environment's state.
  public var skipPypiPackagesInstallation: Swift.Bool = Swift.Bool()

  /// Whether or not to skip setting environment variables when loading the
  /// environment's state.
  public var skipEnvironmentVariablesSetting: Swift.Bool = Swift.Bool()

  /// Whether or not to skip setting Airflow overrides when loading the
  /// environment's state.
  public var skipAirflowOverridesSetting: Swift.Bool = Swift.Bool()

  /// Whether or not to skip copying Cloud Storage data when loading the
  /// environment's state.
  public var skipGcsDataCopying: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `LoadSnapshotRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoadSnapshotRequest().with { $0.environment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.LoadSnapshotRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
