// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The configuration information for the Kubernetes Engine nodes running
/// the Apache Airflow software.
public struct NodeConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The Compute Engine [zone](/compute/docs/regions-zones) in which
  /// to deploy the VMs used to run the Apache Airflow software, specified as a
  /// [relative resource
  /// name](/apis/design/resource_names#relative_resource_name). For example:
  /// "projects/{projectId}/zones/{zoneId}".
  ///
  /// This `location` must belong to the enclosing environment's project and
  /// location. If both this field and `nodeConfig.machineType` are specified,
  /// `nodeConfig.machineType` must belong to this `location`; if both are
  /// unspecified, the service will pick a zone in the Compute Engine region
  /// corresponding to the Cloud Composer location, and propagate that choice to
  /// both fields. If only one field (`location` or `nodeConfig.machineType`) is
  /// specified, the location information from the specified field will be
  /// propagated to the unspecified field.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var location: Swift.String = Swift.String()

  /// Optional. The Compute Engine
  /// [machine type](/compute/docs/machine-types) used for cluster instances,
  /// specified as a
  /// [relative resource
  /// name](/apis/design/resource_names#relative_resource_name). For example:
  /// "projects/{projectId}/zones/{zoneId}/machineTypes/{machineTypeId}".
  ///
  /// The `machineType` must belong to the enclosing environment's project and
  /// location. If both this field and `nodeConfig.location` are specified,
  /// this `machineType` must belong to the `nodeConfig.location`; if both are
  /// unspecified, the service will pick a zone in the Compute Engine region
  /// corresponding to the Cloud Composer location, and propagate that choice to
  /// both fields. If exactly one of this field and `nodeConfig.location` is
  /// specified, the location information from the specified field will be
  /// propagated to the unspecified field.
  ///
  /// The `machineTypeId` must not be a [shared-core machine
  /// type](/compute/docs/machine-types#sharedcore).
  ///
  /// If this field is unspecified, the `machineTypeId` defaults
  /// to "n1-standard-1".
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var machineType: Swift.String = Swift.String()

  /// Optional. The Compute Engine network to be used for machine
  /// communications, specified as a
  /// [relative resource
  /// name](/apis/design/resource_names#relative_resource_name). For example:
  /// "projects/{projectId}/global/networks/{networkId}".
  ///
  /// If unspecified, the "default" network ID in the environment's project is
  /// used. If a [Custom Subnet Network](/vpc/docs/vpc#vpc_networks_and_subnets)
  /// is provided, `nodeConfig.subnetwork` must also be provided. For
  /// [Shared VPC](/vpc/docs/shared-vpc) subnetwork requirements, see
  /// `nodeConfig.subnetwork`.
  public var network: Swift.String = Swift.String()

  /// Optional. The Compute Engine subnetwork to be used for machine
  /// communications, specified as a
  /// [relative resource
  /// name](/apis/design/resource_names#relative_resource_name). For example:
  /// "projects/{projectId}/regions/{regionId}/subnetworks/{subnetworkId}"
  ///
  /// If a subnetwork is provided, `nodeConfig.network` must also be provided,
  /// and the subnetwork must belong to the enclosing environment's project and
  /// location.
  public var subnetwork: Swift.String = Swift.String()

  /// Optional. The disk size in GB used for node VMs. Minimum size is 30GB.
  /// If unspecified, defaults to 100GB. Cannot be updated.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var diskSizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. The set of Google API scopes to be made available on all
  /// node VMs. If `oauth_scopes` is empty, defaults to
  /// ["https://www.googleapis.com/auth/cloud-platform"]. Cannot be updated.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var oauthScopes: [Swift.String] = []

  /// Optional. The Google Cloud Platform Service Account to be used by the node
  /// VMs. If a service account is not specified, the "default" Compute Engine
  /// service account is used. Cannot be updated.
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. The list of instance tags applied to all node VMs. Tags are used
  /// to identify valid sources or targets for network firewalls. Each tag within
  /// the list must comply with [RFC1035](https://www.ietf.org/rfc/rfc1035.txt).
  /// Cannot be updated.
  public var tags: [Swift.String] = []

  /// Optional. The configuration for controlling how IPs are allocated in the
  /// GKE cluster.
  public var ipAllocationPolicy: IPAllocationPolicy? = nil

  /// Optional. Deploys 'ip-masq-agent' daemon set in the GKE cluster and defines
  /// nonMasqueradeCIDRs equals to pod IP range so IP masquerading is used for
  /// all destination addresses, except between pods traffic.
  ///
  /// See:
  /// https://cloud.google.com/kubernetes-engine/docs/how-to/ip-masquerade-agent
  public var enableIpMasqAgent: Swift.Bool = Swift.Bool()

  /// Optional. Network Attachment that Cloud Composer environment is connected
  /// to, which provides connectivity with a user's VPC network. Takes precedence
  /// over network and subnetwork settings. If not provided, but network and
  /// subnetwork are defined during environment, it will be provisioned. If not
  /// provided and network and subnetwork are also empty, then connectivity to
  /// user's VPC network is disabled. Network attachment must be provided in
  /// format
  /// projects/{project}/regions/{region}/networkAttachments/{networkAttachment}.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public var composerNetworkAttachment: Swift.String = Swift.String()

  /// Optional. The IP range in CIDR notation to use internally by Cloud
  /// Composer. IP addresses are not reserved - and the same range can be used by
  /// multiple Cloud Composer environments. In case of overlap, IPs from this
  /// range will not be accessible in the user's VPC network. Cannot be updated.
  /// If not specified, the default value of '100.64.128.0/20' is used.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public var composerInternalIpv4CidrBlock: Swift.String = Swift.String()

  /// Initialize a new instance of `NodeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodeConfig().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.NodeConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
