// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The configuration information for configuring a Private IP Cloud Composer
/// environment.
public struct PrivateEnvironmentConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. If `true`, a Private IP Cloud Composer environment is created.
  /// If this field is set to true, `IPAllocationPolicy.use_ip_aliases` must be
  /// set to true for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var enablePrivateEnvironment: Swift.Bool = Swift.Bool()

  /// Optional. If `true`, builds performed during operations that install Python
  /// packages have only private connectivity to Google services (including
  /// Artifact Registry) and VPC network (if either `NodeConfig.network` and
  /// `NodeConfig.subnetwork` fields or `NodeConfig.composer_network_attachment`
  /// field are specified). If `false`, the builds also have access to the
  /// internet.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public var enablePrivateBuildsOnly: Swift.Bool = Swift.Bool()

  /// Optional. Configuration for the private GKE cluster for a Private IP
  /// Cloud Composer environment.
  public var privateClusterConfig: PrivateClusterConfig? = nil

  /// Optional. The CIDR block from which IP range for web server will be
  /// reserved. Needs to be disjoint from
  /// `private_cluster_config.master_ipv4_cidr_block` and
  /// `cloud_sql_ipv4_cidr_block`.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var webServerIpv4CidrBlock: Swift.String = Swift.String()

  /// Optional. The CIDR block from which IP range in tenant project will be
  /// reserved for Cloud SQL. Needs to be disjoint from
  /// `web_server_ipv4_cidr_block`.
  public var cloudSqlIpv4CidrBlock: Swift.String = Swift.String()

  /// Output only. The IP range reserved for the tenant project's App Engine VMs.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var webServerIpv4ReservedRange: Swift.String = Swift.String()

  /// Optional. The CIDR block from which IP range for Cloud Composer Network in
  /// tenant project will be reserved. Needs to be disjoint from
  /// private_cluster_config.master_ipv4_cidr_block and
  /// cloud_sql_ipv4_cidr_block.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  public var cloudComposerNetworkIpv4CidrBlock: Swift.String = Swift.String()

  /// Output only. The IP range reserved for the tenant project's Cloud Composer
  /// network.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  public var cloudComposerNetworkIpv4ReservedRange: Swift.String = Swift.String()

  /// Optional. When enabled, IPs from public (non-RFC1918) ranges can be used
  /// for `IPAllocationPolicy.cluster_ipv4_cidr_block` and
  /// `IPAllocationPolicy.service_ipv4_cidr_block`.
  public var enablePrivatelyUsedPublicIps: Swift.Bool = Swift.Bool()

  /// Optional. When specified, the environment will use Private Service Connect
  /// instead of VPC peerings to connect to Cloud SQL in the Tenant Project,
  /// and the PSC endpoint in the Customer Project will use an IP address from
  /// this subnetwork.
  public var cloudComposerConnectionSubnetwork: Swift.String = Swift.String()

  /// Optional. Configuration for the network connections configuration in the
  /// environment.
  public var networkingConfig: NetworkingConfig? = nil

  /// Initialize a new instance of `PrivateEnvironmentConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivateEnvironmentConfig().with { $0.enablePrivateEnvironment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PrivateEnvironmentConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
