// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The configuration for scheduled snapshot creation mechanism.
public struct ScheduledSnapshotsConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether scheduled snapshots creation is enabled.
  public var enabled: Swift.Bool = Swift.Bool()

  /// Optional. The Cloud Storage location for storing automatically created
  /// snapshots.
  public var snapshotLocation: Swift.String = Swift.String()

  /// Optional. The cron expression representing the time when snapshots creation
  /// mechanism runs. This field is subject to additional validation around
  /// frequency of execution.
  public var snapshotCreationSchedule: Swift.String = Swift.String()

  /// Optional. Time zone that sets the context to interpret
  /// snapshot_creation_schedule.
  public var timeZone: Swift.String = Swift.String()

  /// Initialize a new instance of `ScheduledSnapshotsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScheduledSnapshotsConfig().with { $0.enabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ScheduledSnapshotsConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
