// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Network-level access control policy for the Airflow web server.
public struct WebServerNetworkAccessControl: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A collection of allowed IP ranges with descriptions.
  public var allowedIpRanges: [WebServerNetworkAccessControl.AllowedIpRange] = []

  /// Initialize a new instance of `WebServerNetworkAccessControl`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WebServerNetworkAccessControl().with { $0.allowedIpRanges = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Allowed IP range with user-provided description.
  public struct AllowedIpRange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// IP address or range, defined using CIDR notation, of requests that this
    /// rule applies to.
    /// Examples: `192.168.1.1` or `192.168.0.0/16` or `2001:db8::/32`
    ///           or `2001:0db8:0000:0042:0000:8a2e:0370:7334`.
    ///
    /// IP range prefixes should be properly truncated. For example,
    /// `1.2.3.4/24` should be truncated to `1.2.3.0/24`. Similarly, for IPv6,
    /// `2001:db8::1/32` should be truncated to `2001:db8::/32`.
    public var value: Swift.String = Swift.String()

    /// Optional. User-provided description. It must contain at most 300
    /// characters.
    public var description: Swift.String = Swift.String()

    /// Initialize a new instance of `AllowedIpRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AllowedIpRange().with { $0.value = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WebServerNetworkAccessControl.AllowedIpRange"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WebServerNetworkAccessControl"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
