// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The Kubernetes workloads configuration for GKE cluster associated with the
/// Cloud Composer environment. Supported for Cloud Composer environments in
/// versions composer-2.*.*-airflow-*.*.* and newer.
public struct WorkloadsConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Resources used by Airflow schedulers.
  public var scheduler: WorkloadsConfig.SchedulerResource? = nil

  /// Optional. Resources used by Airflow web server.
  public var webServer: WorkloadsConfig.WebServerResource? = nil

  /// Optional. Resources used by Airflow workers.
  public var worker: WorkloadsConfig.WorkerResource? = nil

  /// Optional. Resources used by Airflow triggerers.
  public var triggerer: WorkloadsConfig.TriggererResource? = nil

  /// Optional. Resources used by Airflow DAG processors.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public var dagProcessor: WorkloadsConfig.DagProcessorResource? = nil

  /// Initialize a new instance of `WorkloadsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkloadsConfig().with { $0.scheduler = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Configuration for resources used by Airflow schedulers.
  public struct SchedulerResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for a single Airflow scheduler replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow scheduler
    /// replica.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for a single Airflow scheduler
    /// replica.
    public var storageGb: Swift.Float = Swift.Float()

    /// Optional. The number of schedulers.
    public var count: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `SchedulerResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SchedulerResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.SchedulerResource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow web server.
  public struct WebServerResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for Airflow web server.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for Airflow web server.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for Airflow web server.
    public var storageGb: Swift.Float = Swift.Float()

    /// Initialize a new instance of `WebServerResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WebServerResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.WebServerResource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow workers.
  public struct WorkerResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for a single Airflow worker replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow worker
    /// replica.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for a single Airflow worker
    /// replica.
    public var storageGb: Swift.Float = Swift.Float()

    /// Optional. Minimum number of workers for autoscaling.
    public var minCount: Swift.Int32 = Swift.Int32()

    /// Optional. Maximum number of workers for autoscaling.
    public var maxCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `WorkerResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WorkerResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.WorkerResource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow triggerers.
  public struct TriggererResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The number of triggerers.
    public var count: Swift.Int32 = Swift.Int32()

    /// Optional. CPU request and limit for a single Airflow triggerer replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow triggerer
    /// replica.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Initialize a new instance of `TriggererResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TriggererResource().with { $0.count = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.TriggererResource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow DAG processors.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public struct DagProcessorResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for a single Airflow DAG processor
    /// replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow DAG
    /// processor replica.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for a single Airflow DAG
    /// processor replica.
    public var storageGb: Swift.Float = Swift.Float()

    /// Optional. The number of DAG processors. If not provided or set to 0, a
    /// single DAG processor instance will be created.
    public var count: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `DagProcessorResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DagProcessorResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.DagProcessorResource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
